# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff4c816c9f99f0315618e0a27807a612105d406e33efcdd0acab0736f980f7684dfca7fa09b40b7e03e335d1087202f83da9dafc35605c4f2e593db4f8b5fe94

test:
  secret_key_base: 63b9762a9b58bf7be7a011cfa86327a52cd07d06e7f6d5383b233acecbb0feefe2ee1cb422e90938ffdfbd882b08b7b1324e949dbaf87331b3e265b281f24339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
